package network;

public enum messageType {
    NONE,
    LOGIN,
    LOGINFAILED,
    LOGINSUCCEED,
    REGISTER,
    REGISTERSUCCESS,
    REGISTERFAIL,
    LOADCATALOG,
    CHECKOUT,
    CHECKOUTFAIL,
    CHECKOUTSUCCESS,
    UPDATE,
    RETURN,
    RESERVE,
    RESERVESUCCESS,
    UNRESERVE,
    UPDATEONE,
    RESERVEONE,
    SEARCH
}
